2018-04-14 18:55:58,281 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.2.dev0
2018-04-14 18:55:58,281 [WARNING] mongo_connector.connector:1247 - This is a development version (2.5.2.dev0) of mongo-connector
2018-04-14 18:55:58,281 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
2018-04-14 18:55:58,281 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.10.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
2018-04-14 18:55:58,282 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.6.1
2018-04-14 18:55:58,282 [WARNING] mongo_connector.connector:167 - MongoConnector: Can't find /solr/solr-5.5.4/server/solr/carddb/conf/oplog.timestamp, attempting to create an empty progress log
2018-04-14 18:55:58,911 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.6.3
2018-04-14 18:55:58,912 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.solr_doc_manager version: 0.1.0
2018-04-14 18:57:45,525 [WARNING] mongo_connector.oplog_manager:683 - Initial collection dump was interrupted. Will re-run the collection dump on next startup.
2018-04-14 18:58:20,894 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.2.dev0
2018-04-14 18:58:20,894 [WARNING] mongo_connector.connector:1247 - This is a development version (2.5.2.dev0) of mongo-connector
2018-04-14 18:58:20,894 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
2018-04-14 18:58:20,894 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.10.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
2018-04-14 18:58:20,895 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.6.1
2018-04-14 18:58:20,901 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.6.3
2018-04-14 18:58:20,902 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.solr_doc_manager version: 0.1.0
2018-04-14 19:02:20,973 [ERROR] mongo_connector.util:106 - Fatal Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.5.2.dev0-py2.7.egg/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.5.2.dev0-py2.7.egg/mongo_connector/connector.py", line 404, in run
    self.write_oplog_progress()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.5.2.dev0-py2.7.egg/mongo_connector/connector.py", line 246, in write_oplog_progress
    os.rename(self.oplog_checkpoint, backup_file)
OSError: [Errno 2] No such file or directory
